declare module "virtual:af-resume-entries" {
  import type * as Portable from "effect-atom-jsx/Portable";

  /**
   * Generated by the resume-extract Vite plugin: lazy resolver entries for
   * every compiler-extracted code definition, keyed by code identity. The
   * loaders wrap dynamic imports of the transformed application modules, so
   * the resolver counts below reflect real module-load behavior.
   */
  export const resolverEntries: Portable.ResolverEntries;
}
